get http://localhost:4501/api/productos/618afaf56d55c19c7f2d750f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjE4YWVjM2MwMTliNWU2NWMwOTYyMjhiIn0sImlhdCI6MTYzODM5NjE0NywiZXhwIjoxNjM4Mzk5NzQ3fQ.NrOiZLe0il-w4V-mSJllA_Lq2JG5OmTLQoP2MfkrQMc