POST  http://localhost:4501/api/productos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjFlNWRhODQ1MzlmNDBiMTMxNGRmMTkyIn0sImlhdCI6MTY0MjcxNjE5OSwiZXhwIjoxNjQyNzE5Nzk5fQ.hFfECi7Dz2_maCYpOwpjr3zXI4UTDsfINAB3oHBss1c


{
    "eliminado":false,
    "nombre":"computadora",
    "precio":"7500",
    "descripcion":"nuevo",
    "usuario":"61bbb394319c6eb30879af4f",
    "usuario":"61e5da84539f40b1314df192"


}